### ISSUE TITLE
Ошибка в обновленние

### ISSUE THREAD

**Issue by MikeWoWOne** [ImmortalHostage/Resources_Checker_Base#4]
Исправлена ошибка Bad DemoPlayer.dll
После обновления улетела в бан пол сервера, которые играли со стима. DemoPlayer стима не был учтен в базе как я понял?

**Comment by ImmortalHostage** [comment]
> Исправлена ошибка Bad DemoPlayer.dll
> После обновления улетела в бан пол сервера, которые играли со стима. DemoPlayer стима не был учтен в базе как я понял?

Рекомендую вообще отключить эти проверки.

**Comment by ImmortalHostage** [comment]
Убраны проверки
